version: '3.8'

services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ecommerce
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - ./synthetic_data:/csv_data

  airflow-init:
    image: apache/airflow:2.8.1-python3.10
    depends_on:
      - postgres
    environment:
      AIRFLOW__CORE__EXECUTOR: SequentialExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://postgres:password@postgres:5432/ecommerce
    entrypoint: >
      bash -c "airflow db init &&
               airflow users create --username admin --firstname Jerry --lastname Joseph --role Admin --email jjosepha@gmu.edu --password admin"
    volumes:
      - ./dags:/opt/airflow/dags

  airflow-webserver:
    image: my_custom_airflow:latest
    restart: always
    depends_on:
      - airflow-init
    ports:
      - "8080:8080"
    environment:
      AIRFLOW__CORE__EXECUTOR: SequentialExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://postgres:password@postgres:5432/ecommerce
      AIRFLOW__WEBSERVER__SECRET_KEY: "my_consistent_secret_key"
      AWS_ACCESS_KEY_ID: "${AWS_ACCESS_KEY_ID}"
      AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY}"
      AWS_DEFAULT_REGION: "us-east-1"
    command: webserver
    volumes:
      - ./dags:/opt/airflow/dags
      - ./synthetic_data:/opt/airflow/synthetic_data

  airflow-scheduler:
    image: my_custom_airflow:latest
    restart: always
    depends_on:
      - airflow-webserver
    environment:
      AIRFLOW__CORE__EXECUTOR: SequentialExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://postgres:password@postgres:5432/ecommerce
      AIRFLOW__WEBSERVER__SECRET_KEY: "my_consistent_secret_key"
      AWS_ACCESS_KEY_ID: "${AWS_ACCESS_KEY_ID}"
      AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY}"
      AWS_DEFAULT_REGION: "us-east-1"
    command: scheduler
    volumes:
      - ./dags:/opt/airflow/dags
      - ./synthetic_data:/opt/airflow/synthetic_data

volumes:
  postgres_data: